/*
 * 
 */
package de.github.yfons.rapidfx.examples.HelloWorld;

import de.github.yfons.rapidfx.rapidFX.annotation.RapidfxAutoGenerate;
import de.github.yfons.rapidfx.rapidFX.interfaces.RapidModel;
import de.github.yfons.rapidfx.rapidFX.simple.RapidSimpleModel;
import javafx.beans.property.StringProperty;

//"Buisness Logic" -> Everything that only needs Properties and backend to work
/**
 * The Class LoginModel.
 */
// no Eventhandlers, no Nodes here
public class LoginModel extends RapidSimpleModel implements RapidModel {

  /** The title text property. */
  @RapidfxAutoGenerate
  private StringProperty titleTextProperty;
  // all Properties with the Name SimpleXXXProperty can get Autogenerated, eg
  /** The greetings property. */
  // ObjectProperty, StringProperty,DoubleProperty....
  @RapidfxAutoGenerate
  private StringProperty greetingsProperty;

  /**
   * Sets the up model.
   */
  public void setUpModel() {
    titleTextProperty.set("Hello World");
  }

  /**
   * Login.
   */
  public void login() {
    titleTextProperty.set("You are logged in");
    System.out.println("Hello from the Model");
  }

}
